from termcolor import colored

compName = "Mac"
compAge = 2
compHeight = 0.015

print(colored('''Hi there!

This is a small program to work through a bunch of practicals generated by 
chatGPT to get a good understanding of variables, the most important data 
types and basic operators. 

In addition, I imported my first package to use colours to make the output 
look prettier. 💅
''', 'blue', attrs=['bold']))  # blue text no highlight and in bold -
# attributes like bold, underlined, etc. always have to be in brackets even
# if it's just one value!

# colored() also works on input!
yourName = input(colored("Firstly, tell me your name:",
                         on_color="on_light_magenta", attrs=['bold']))
yourAge = input(colored("And how old are you?", on_color="on_light_magenta",
                        attrs=['bold']))
yourHeight = input(colored("Lastly, I would like to know your height in "
                           "metres.", on_color="on_light_magenta",
                           attrs=['bold']))

# multiple stylings need to be defined seperately!
nameOutput = colored(yourName, 'red', 'on_light_grey', ['bold'])
ageOutput = colored(yourAge, 'red', 'on_light_grey', ['bold'])
heightOutput = colored(yourHeight, 'red', 'on_light_grey', ['bold'])

print('Excellent! So your name is', nameOutput + ', you are', ageOutput,
      'years old and you are', heightOutput, 'm tall.')

# input makes value per default a string. convert it back to a float to
# calculate with it:
heightDifference = float(yourHeight) - compHeight

# concatenation of floats with strings does not work with '+' - use ',' instead:
print('Interesting! You are', heightDifference, 'm taller than me who is',
      compHeight, 'm tall. Or thick.')
# (unfortunately, this leads to a space between numbers and their units.
# Alternative:
print('Interesting! You are', str(heightDifference) +
      'm taller than me who is', str(compHeight) + 'm tall. Or thick.')

print(colored('''
Now, I want you to prompt me with two numbers of your choice. They can be 
inegers or floating point numbers. I will then perform basic arithmetics on 
these two numbers and print out each of the results.
''', 'blue', attrs=['bold']))

# cast the input into a float (also contains integer values) - both methods
# work: either seperaterly after input or cast the input directly
a = input(colored('Please type in your first number:',
                  on_color="on_light_magenta",
                  attrs=['bold']))
a = float(a)

b = float(input(colored('Please type in the second number:',
                        on_color="on_light_magenta",
                        attrs=['bold'])))

sumOf = a + b
differenceA_B = a - b
differenceB_A = b - a
product = a * b
ratioA_B = a / b
ratioB_A = b / a
floorDivisionA = a // b
floorDivisionB = b // a
remainderA_B = a % b
remainderB_A = b % a
powerOfB = a ** b
powerOfA = b ** a

# one single print statement and the 'sep' parameter at the end will do a
# linebreak for every statement
print(
    colored('The sum of these two numbers is:', attrs=['bold']), sumOf,
    colored('The difference of a - b is:', attrs=['bold']), differenceA_B,
    colored('The difference of b - a is:', attrs=['bold']), differenceB_A,
    colored('The product of the two numbers is:', attrs=['bold']), product,
    colored('A divided by b is:', attrs=['bold']), ratioA_B,
    colored('B divided by A is:', attrs=['bold']), ratioB_A,
    colored('A divided by B and rounded to the next lower integer is:', attrs=[
        'bold']), floorDivisionA,
    colored('B divided by A and rounded to the next lower integer is:', attrs=[
        'bold']), floorDivisionB,
    colored('A mod B - or: the remainder of A divided by B is:', attrs=[
        'bold']), remainderA_B,
    colored('B mod A - or: the remainder of B divided by A is:', attrs=[
        'bold']), remainderB_A,
    colored('A to the power of b is:', attrs=['bold']), powerOfB,
    colored('B to the power of A is:', attrs=['bold']), powerOfA,
    sep='\n'
)
